apiVersion: v2
name: skywalking
home: https://skywalking.apache.org
version: 1.0.0
appVersion: 6.5.0
description: Apache SkyWalking APM System
icon: https://raw.githubusercontent.com/apache/skywalking-kubernetes/master/logo/sw-logo-for-chart.jpg
sources:
- https://github.com/apache/skywalking-kubernetes
maintainers:
- name: hanahmily
  email: hanahmily@gmail.com
- name: innerpeacez
  email: innerpeace.zhai@gmail.com

