# Default values for skywalking.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceAccounts:
  oap:

oap:
  name: skywalking-oap
  image:
    repository: apache/skywalking-oap-server
    tag: 6.5.0
    pullPolicy: IfNotPresent
  ports:
    grpc: 11800
    rest: 12800
  replicas: 2
  service:
    type: ClusterIP
  javaOpts: -Xmx2g -Xms2g
  antiAffinity: "soft"
  nodeAffinity: {}
  nodeSelector: {}
  tolerations: []
  resources: {}
    # limits:
    #   cpu: 8
    #   memory: 8Gi
    # requests:
    #   cpu: 8
    #   memory: 4Gi
  # podAnnotations:
  #   example: oap-foo
  envoy:
    als:
      enabled: false
      # more envoy ALS ,please refer to https://github.com/apache/skywalking/blob/master/docs/en/setup/envoy/als_setting.md#observe-service-mesh-through-als
  env:
    # more env, please refer to https://hub.docker.com/r/apache/skywalking-oap-server
    # or https://github.com/apache/skywalking-docker/blob/master/6/6.4/oap/README.md#sw_telemetry
    # es config ref: https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-storage.md 
    SW_STORAGE: elasticsearch
    SW_STORAGE_ES_CLUSTER_NODES_HOST: localhost
    SW_STORAGE_ES_CLUSTER_NODES_PORT: 9200
    SW_STORAGE_ES_CLUSTER_NODES: localhost:9200
    SW_STORAGE_ES_HTTP_PROTOCOL: http
    SW_STORAGE_ES_INDEX_SHARDS_NUMBER: 2
    SW_STORAGE_ES_INDEX_REPLICAS_NUMBER: 0
    SW_STORAGE_ES_RECORD_DATA_TTL: 7
    SW_STORAGE_ES_OTHER_METRIC_DATA_TTL: 30
    SW_STORAGE_ES_MONTH_METRIC_DATA_TTL: 12
    SW_STORAGE_ES_BULK_ACTIONS: 2000
    SW_STORAGE_ES_BULK_SIZE: 20
    SW_STORAGE_ES_FLUSH_INTERVAL: 10
    SW_STORAGE_ES_CONCURRENT_REQUESTS: 2
ui:
  name: skywalking-ui
  replicas: 1
  image:
    repository: apache/skywalking-ui
    tag: 6.5.0
    pullPolicy: IfNotPresent
  # podAnnotations:
  #   example: oap-foo
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts: []
    # - skywalking.local
    tls: []
    #  - secretName: skywalking-tls
    #    hosts:
    #      - skywalking.local
  service:
    type: ClusterIP
    # clusterIP: None
    externalPort: 80
    internalPort: 8080
    ## External IP addresses of service
    ## Default: nil
    ##
    # externalIPs:
    # - 192.168.0.1
    #
    ## LoadBalancer IP if service.type is LoadBalancer
    ## Default: nil
    ##
    # loadBalancerIP: 10.2.2.2
    # Annotation example: setup ssl with aws cert when service.type is LoadBalancer
    # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:EXAMPLE_CERT
    annotations: {}
    ## Limit load balancer source ips to list of CIDRs (where available)
    # loadBalancerSourceRanges: []

nameOverride: ""
